---
version: "3"
services:
  akaunting:
    image: whitlocktech/akaunting:latest
    container_name: akaunting
    volumes:
      -<your path here>config/www:/var/www/akaunting
      - <your path here>/config/nginx:/etc/nginx
    ports:
      - 3186:80
    restart: unless-stopped
